training:  
  epochs: 500  
  batch_size: 32  
  latent_dim: 10  

components:  
  generator:  
    type: "quantum_continuous"  # Options: classical/quantum_discrete/quantum_continuous  
    n_qumodes: 3  
    cutoff_dim: 5  

  discriminator:  
    type: "classical"  
    hidden_units: 64  

optimizer:  
  learning_rate: 0.001  
  beta_1: 0.9  